# Generated by Django 4.1.3 on 2022-11-16 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcoder', '0002_entregable_oviparo_profesor_rename_curso_animal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invertebrado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('bioma', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vertebrado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('bioma', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Entregable',
        ),
        migrations.DeleteModel(
            name='Oviparo',
        ),
        migrations.DeleteModel(
            name='Profesor',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='camada',
        ),
        migrations.AddField(
            model_name='animal',
            name='bioma',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
